version: '3.8'

services:
  migration:
    build: .
    command: sh -c "npm run migrate:up"
    env_file:
      - .env
    depends_on:
      - db

  app:
    build: .
    deploy:
      replicas: 5
    ports:
      - "3000-3004:3000"
    volumes:
      - .:/usr/src/app
    command: sh -c "npm run dev"
    env_file:
      - .env
    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_started

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: