version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
        - .:/usr/src/app
    command: sh -c "npm run start:with-migrations"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: