version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://user:password@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: